nextcloud:
  mysql_host: mysql-service
  mysql_user: nextcloud
  mysql_password: nextcloud
  pv_size: 5Gi
  pv_path: /User/juan/Kubernetes/storage
  pvc_path: 5Gi
  image: nextcloud:stable
  replicas: 1
  externalport: 80

mysql:
  mysql_root_password: nextcloud
  mysql_database: nextcloud
  image: mysql:8.2.0
  pv_size: 1Gi
  pv_path: /User/juan/Kubernetes/storage
  pvc_size: 1Gi

prometheus:
  image: prom/prometheus:v2.47.2
  externalport: 8081

grafana:
  default_user: admin
  default_password: admin
  image: grafana/grafana:10.2.0
  externalport: 8080

node_exporter:
  image: prom/node-exporter:v1.6.1
  cpulimit: 2
  cpurequest: 1
  memorylimit: 1000Mi
  memoryrequest: 500Mi
