kind: ConfigMap
apiVersion: v1
metadata:
  name: configmap
data:
  #mysql
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.mysql_root_password }}
  MYSQL_DATABASE: {{ .Values.mysql.mysql_database }}
  #Nextcloud
  MYSQL_HOST: {{ .Values.nextcloud.mysql_host }} #nombre del servicio mysql
  MYSQL_USER: {{ .Values.nextcloud.mysql_user }}
  MYSQL_PASSWORD: {{ .Values.nextcloud.mysql_password }}
  ##Prometheus
  prometheus.yml: |-
    global:
      scrape_interval: 3s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'node_exporter'
        static_configs:
          - targets: ['node-exporter:9100']
  ##Grafana
  GF_SECURITY_ADMIN_USER: {{ .Values.grafana.default_user }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.grafana.default_password }}
