apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app: grafana
  ports:
    - name: web
      port: {{ .Values.grafana.externalport }}
      targetPort: 3000
  type: LoadBalancer
