apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: {{ .Values.mysql.pv_size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.mysql.pv_path }}
