apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-deployment
spec:
  replicas: {{ .Values.nextcloud.replicas }}
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: {{ .Values.nextcloud.image }}
          #livenessProbe:
          #  httpGet:
          #    path: /index.php
          #    port: 80
          #  initialDelaySeconds: 30
          #  periodSeconds: 30
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: configmap
          volumeMounts:
            - name: nextcloud-data
              mountPath: /var/www/html/data
      volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-data-pvc
