apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data-pv
spec:
  capacity:
    storage: {{ .Values.nextcloud.pv_size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.nextcloud.pv_path }}
