apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
spec:
  selector:
    app: nextcloud
  ports:
    - protocol: TCP
      port: {{ .Values.nextcloud.externalport }}
      targetPort: 80
  type: LoadBalancer
