apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  labels:
    app: node-exporter
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: node-exporter
    spec:
      containers:
        - name: node-exporter
          image: {{ .Values.node_exporter.image }}
          ports:
            - containerPort: 9100
          resources:
            limits:
              cpu: "{{ .Values.node_exporter.cpulimit }}"
              memory: "{{ .Values.node_exporter.memorylimit }}"
            requests:
              cpu: "{{ .Values.node_exporter.cpurequest }}"
              memory: "{{ .Values.node_exporter.memoryrequest }}"
