apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9100'
spec:
  selector:
    app: prometheus
  ports:
    - name: web
      port: 8081
      targetPort: 9090
  type: LoadBalancer
